chore(master): check pre-release creation

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -7,11 +7,11 @@ CYAN='\033[0;36m'
 NC='\033[0m'
 
 BRANCH_NAME="$(git branch | grep \* | sed -e 's/\* //g')"
-#if [[ -z "$BRANCH_NAME" ]] || [ "$BRANCH_NAME" != "master" ]; then
-#    # if branch is different then master do not run tests
-#    exit 0
-#else
-#    echo -e "\t${RED}Push Aborted - Pushing to master only available from github pull requests${NC}"
-#    exit 1
-#fi
+if [[ -z "$BRANCH_NAME" ]] || [ "$BRANCH_NAME" != "master" ]; then
+    # if branch is different then master do not run tests
+    exit 0
+else
+    echo -e "\t${RED}Push Aborted - Pushing to master only available from github pull requests${NC}"
+    exit 1
+fi
 
